# Generated by Django 4.0 on 2021-12-16 15:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Building'), (2, 'fountain'), (3, 'furniture'), (4, 'Home equipment'), (5, 'natural')], default=1),
        ),
        migrations.AlterField(
            model_name='health',
            name='get_covid_19',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='participant',
            name='education_level',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='question',
            name='order_index',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='score',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(1)]),
        ),
    ]
