# Generated by Django 4.0 on 2021-12-16 15:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0002_image_category_alter_health_get_covid_19_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='participant',
            name='next_task_date',
        ),
        migrations.CreateModel(
            name='TaskEventImageReactionTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_time', models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(180)])),
                ('Image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='task_app.image')),
                ('task_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_app.taskevent')),
            ],
        ),
        migrations.AddField(
            model_name='taskevent',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_app.participant'),
        ),
        migrations.CreateModel(
            name='ParticipantQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_app.questionanswer')),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='task_app.participant')),
            ],
            options={
                'unique_together': {('participant', 'answer')},
            },
        ),
    ]
