# Generated by Django 4.0 on 2021-12-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0003_taskevent_remove_participant_next_task_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='picture',
            field=models.TextField(),
        ),
    ]
