# Generated by Django 4.0 on 2021-12-16 17:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0005_alter_image_picture'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participantquestionanswer',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='participantquestionanswer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task_app.question'),
        ),
        migrations.AlterField(
            model_name='participantquestionanswer',
            name='answer',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterUniqueTogether(
            name='participantquestionanswer',
            unique_together={('participant', 'question', 'answer')},
        ),
        migrations.DeleteModel(
            name='QuestionAnswer',
        ),
    ]
