# Generated by Django 4.0 on 2021-12-16 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0006_alter_participantquestionanswer_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantquestionanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_app.question'),
        ),
    ]
