# Generated by Django 4.0 on 2021-12-17 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0008_alter_participantquestionanswer_participant'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participantquestionanswer',
            unique_together={('participant', 'question')},
        ),
    ]
