# Generated by Django 4.0 on 2021-12-17 10:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0009_alter_participantquestionanswer_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskeventimagereactiontime',
            name='reaction_time',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(3000)]),
        ),
    ]
