# Generated by Django 4.0 on 2021-12-17 13:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0010_alter_taskeventimagereactiontime_reaction_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='birthday',
        ),
        migrations.AddField(
            model_name='participant',
            name='birth_year',
            field=models.IntegerField(default=1320, validators=[django.core.validators.MaxValueValidator(1410), django.core.validators.MinValueValidator(1270)]),
        ),
        migrations.AlterField(
            model_name='participant',
            name='mobile_number',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^09[0-9]{9}$', message='شماره ی موبایل معتبر نمیباشد.')]),
        ),
    ]
