# Generated by Django 4.0 on 2021-12-19 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0011_remove_participant_birthday_participant_birth_year_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskeventimagereactiontime',
            old_name='Image',
            new_name='image',
        ),
    ]
