# Generated by Django 4.0 on 2022-01-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0012_rename_image_taskeventimagereactiontime_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'sakhteman'), (2, 'fountain'), (3, 'furniture'), (4, 'kettle'), (5, 'landscap'), (6, 'spoon'), (7, 'tools'), (8, 'town'), (9, 'tree'), (10, 'flower')], default=1),
        ),
    ]
