# Generated by Django 4.0 on 2022-02-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0013_alter_image_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='category',
            field=models.CharField(choices=[('towner', 'towner'), ('fountain', 'fountain'), ('furniture', 'furniture'), ('kettle', 'kettle'), ('landscap', 'landscap'), ('spoon', 'spoon'), ('tools', 'tools'), ('town', 'town'), ('tree', 'tree'), ('flower', 'flower')], default='towner', max_length=10),
        ),
    ]
