# Generated by Django 4.0 on 2022-03-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0016_health_get_medicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='category',
            field=models.CharField(choices=[('towner', 'towner'), ('fountain', 'fountain'), ('furniture', 'furniture'), ('kettle', 'kettle'), ('landscap', 'landscap'), ('spoon', 'spoon'), ('tools', 'tools'), ('tree', 'tree'), ('flower', 'flower'), ('test', 'test')], default='towner', max_length=10),
        ),
    ]
