# Generated by Django 4.0 on 2022-03-28 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0017_alter_image_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='mobile_number',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
